### ISSUE TITLE
Android O, nexus 5x SIGABRT crash

### ISSUE THREAD

**Issue by ar-g** [facebook/fresco#1885]
### Description

After using app around 3 min it crashes on nexus 5x. Stacktrace:

```
09-03 12:38:48.525 25260-25268/com.lalafo A/libc: Invalid address 0x7b3d6ff180 passed to free: value not allocated
09-03 12:38:48.821 2640-25268/? A/google-breakpad: Microdump skipped (uninteresting)
09-03 12:38:48.864 25260-25268/com.lalafo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 25268 (ReferenceQueueD)
09-03 12:38:49.022 2651-2651/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-03 12:38:49.022 2651-2651/? A/DEBUG: Build fingerprint: 'google/bullhead/bullhead:8.0.0/OPR6.170623.013/4283548:user/release-keys'
09-03 12:38:49.022 2651-2651/? A/DEBUG: Revision: 'rev_1.0'
09-03 12:38:49.022 2651-2651/? A/DEBUG: ABI: 'arm64'
09-03 12:38:49.022 2651-2651/? A/DEBUG: pid: 25260, tid: 25268, name: ReferenceQueueD  >>> com.lalafo <<<
09-03 12:38:49.022 2651-2651/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-03 12:38:49.030 2651-2651/? A/DEBUG: Abort message: 'Invalid address 0x7b3d6ff180 passed to free: value not allocated'
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x0   0000000000000000  x1   00000000000062b4  x2   0000000000000006  x3   0000000000000008
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x4   8080808080808080  x5   8080808080808080  x6   8080808080808080  x7   0000000000000008
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x8   0000000000000083  x9   d3dc3b1190c8230a  x10  0000000000000000  x11  0000000000000001
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x12  0000000000000000  x13  0000000000000000  x14  0000000000000000  x15  001f4f90a96e252c
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x16  0000007b646712f8  x17  0000007b646131d4  x18  0000000000000017  x19  00000000000062ac
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x20  00000000000062b4  x21  0000007b6185e800  x22  0000000000000000  x23  0000007b6467c878
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x24  0000000016198b68  x25  0000007b5537a498  x26  0000000000000000  x27  0000000000000002
09-03 12:38:49.030 2651-2651/? A/DEBUG:     x28  0000000000000001  x29  0000007b4aa75090  x30  0000007b645c6780
09-03 12:38:49.030 2651-2651/? A/DEBUG:     sp   0000007b4aa75050  pc   0000007b646131dc  pstate 0000000060000000
09-03 12:38:49.086 2651-2651/? A/DEBUG: backtrace:
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #00 pc 000000000006a1dc  /system/lib64/libc.so (tgkill+8)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #01 pc 000000000001d77c  /system/lib64/libc.so (abort+88)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #02 pc 0000000000025134  /system/lib64/libc.so (__libc_fatal+116)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #03 pc 0000000000091958  /system/lib64/libc.so (ifree+824)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #04 pc 0000000000091bd8  /system/lib64/libc.so (je_free+120)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #05 pc 0000000000021f9c  /system/lib64/libjavacore.so (_ZL12Matcher_freePv+68)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #06 pc 00000000003053c0  /system/framework/arm64/boot-core-libart.oat (offset 0xd6000) (java.math.NativeBN.BN_copy [DEDUPED]+160)
09-03 12:38:49.086 2651-2651/? A/DEBUG:     #07 pc 000000000004a45c  /dev/ashmem/dalvik-jit-code-cache (deleted)
```

**Comment by lambdapioneer** [comment]
Hey @ar-g this looks like a double-free or a bad-reference-free. From the logcat I cannot narrow this down to Fresco. Do you have more details such as:

 - Does it only reproduce when using Fresco?
 - Can you provide a full log?
 - What's the device model?
 - How can we reproduce this error?

**Comment by ar-g** [comment]
What could be the reason of double-free or bad-reference-free? Could it be because of clearing fresco cache?

1. Can not say for now.
2.
```
backtrace:
  native: pc 0000000000091678  /system/lib64/libc.so (ifree+88)
  native: pc 0000000000091bd8  /system/lib64/libc.so (je_free+120)
  native: pc 0000000000021f9c  /system/lib64/libjavacore.so (_ZL12Matcher_freePv+68)
  native: pc 00000000003053c0  /system/framework/arm64/boot-core-libart.oat (java.math.NativeBN.BN_copy [DEDUPED]+160)
  native: pc 000000000033eefc  /system/framework/arm64/boot-core-libart.oat (libcore.util.NativeAllocationRegistry$CleanerThunk.run+76)
  native: pc 00000000006e4078  /system/framework/arm64/boot.oat (sun.misc.Cleaner.clean+136)
  native: pc 00000000002dc3cc  /system/framework/arm64/boot.oat (java.lang.ref.ReferenceQueue.enqueueLocked+268)
  native: pc 00000000002dc59c  /system/framework/arm64/boot.oat (java.lang.ref.ReferenceQueue.enqueuePending+188)
  native: pc 00000000002e77fc  /system/framework/arm64/boot-core-libart.oat (java.lang.Daemons$ReferenceQueueDaemon.runInternal+252)
  native: pc 00000000002e5f3c  /system/framework/arm64/boot-core-libart.oat (java.lang.Daemons$Daemon.run+76)
  native: pc 00000000001fbc0c  /system/framework/arm64/boot.oat (java.lang.Thread.run+76)
  native: pc 000000000050e784  /system/lib64/libart.so (art_quick_invoke_stub+580)
  native: pc 00000000000d80d4  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+208)
  native: pc 0000000000436994  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+104)
  native: pc 0000000000437b3c  /system/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue+432)
  native: pc 000000000045e11c  /system/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1140)
  native: pc 0000000000066a4c  /system/lib64/libc.so (_ZL15__pthread_startPv+36)
  native: pc 000000000001eb94  /system/lib64/libc.so (__start_thread+68)
```
3. LGE Nexus 5X (bullhead), 2048MB RAM, Android 8.0
4. It happens randomly after using app for some time
